### ISSUE TITLE
ValueError : cannot determine volume type %s

### ISSUE THREAD

**Issue by Volcanios** [adammillerio/cratedigger#5]
cratedigger has always been working, today i sync as everytime by doing cratedigger sync --library-dir=D:\lucas\Mix2

But it raises this error

INFO:cratedigger.commands.sync:Loading media library from D:/lucas/Mix2
Traceback (most recent call last):
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\Scripts\cratedigger-script.py", line 33, in <module>
    sys.exit(load_entry_point('cratedigger==1.0.2', 'console_scripts', 'cratedigger')())
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\cratedigger\commands\sync.py", line 26, in cli
    media_library.load(library_dir)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\cratedigger\media\library.py", line 54, in load
    self.split_volume(path)
  File "C:\Users\lucas\AppData\Local\Programs\Python\Python310\lib\site-packages\cratedigger\serato\library.py", line 258, in split_volume
    raise ValueError('Cannot determine volume type for "%s"')
ValueError: Cannot determine volume type for "%s"

![image](https://user-images.githubusercontent.com/62264295/197027005-01e87b60-a311-4b02-81b5-06c2589a8a7f.png)

Do you have any hint ?

**Comment by Volcanios** [comment]
the path wasn't correct, it's D:\\\lucas\Mix2

**Comment by manimash70** [comment]
Used the command from homebrew to install packages. Getting -bash: cratedigger: command not found after homebrew completed installation
